In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pakistan-2022-full-data/Pakistan-2022-full-data.dta

In [2]:
df = pd.read_stata("/kaggle/input/pakistan-2022-full-data/Pakistan-2022-full-data.dta")
df.head()

,idstd,id,a4a,a6a,a2,panel,a4b_v4,a0,a3a,a6c,...,a4b,ic1,stratificationregioncode,stratificationsizecode,stratificationsectorcode,stratificationpanelcode,wstrict,wmedian,wweak,strata
0,1012049,1,Food,Medium,Islamabad,Panel,Food,Manufacturing,Islamabad,38,...,15,Yes,Islamabad,Medium (20-99),Food,Panel,1.569601,1.584625,1.548107,212
1,1012050,6,Food,Medium,Islamabad,Panel,Food,Manufacturing,Islamabad,35,...,15,Yes,Islamabad,Medium (20-99),Food,Panel,1.408249,1.402892,1.396703,212
2,1012051,7,Food,Medium,Islamabad,Panel,Food,Manufacturing,Islamabad,80,...,15,Yes,Islamabad,Medium (20-99),Food,Panel,1.408249,1.402892,1.396703,212
3,1012052,8,Food,Medium,Sindh,Panel,Food and beverage,Other services,Sindh,31,...,55,Yes,Sindh,Medium (20-99),Food,Panel,25.144453,25.144453,25.146425,79
4,1012053,9,Food,Medium,Sindh,Panel,Food and beverage,Other services,Sindh,60,...,55,Yes,Sindh,Medium (20-99),Food,Panel,25.144453,25.144453,25.146425,79

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Columns: 434 entries, idstd to strata
dtypes: category(352), float32(3), float64(14), int16(7), int32(2), int8(40), object(16)
memory usage: 1.1+ MB

In [4]:
df.describe()

,idstd,id,a6c,a14d,a14m,a14y,a14h,a14min,a1,competition_select,...,a19h,a19m,a13,d1a2_v4,d1a2,a4b,wstrict,wmedian,wweak,strata
count,1.300000e+03,1300.000000,1300.000000,1300.000000,1300.000000,1300.0,1300.000000,1300.000000,1300.0,1300.000000,...,198.000000,198.000000,1300.000000,1300.000000,1300.000000,1300.000000,1300.000000,1300.000000,1300.000000,1300.000000
mean,1.012698e+06,16529.560769,104.034615,15.898462,8.592308,2022.0,13.133846,28.590000,90.0,0.512308,...,1.474747,17.994949,1.919231,3009.889231,3382.074615,33.495385,88.466347,88.477310,88.483330,91.297692
std,3.754220e+02,15215.744168,333.481940,8.777490,2.236227,0.0,2.972638,17.513274,0.0,0.500041,...,0.975262,18.280804,0.920437,1582.711802,1527.221207,15.286864,118.424423,118.455208,118.499359,68.585061
min,1.012049e+06,1.000000,2.000000,1.000000,5.000000,2022.0,0.000000,0.000000,90.0,0.000000,...,0.000000,0.000000,1.000000,1010.000000,1511.000000,15.000000,1.000000,1.000000,1.000000,1.000000
25%,1.012374e+06,706.750000,12.000000,7.000000,7.000000,2022.0,11.000000,13.000000,90.0,0.000000,...,1.000000,1.000000,1.000000,1430.000000,1810.000000,18.000000,7.214286,7.214286,7.214286,29.000000
50%,1.012698e+06,18367.000000,27.500000,18.000000,8.000000,2022.0,13.000000,28.000000,90.0,1.000000,...,1.000000,15.000000,2.000000,2396.000000,2710.000000,27.000000,22.535398,22.535398,22.535398,79.000000
75%,1.013023e+06,32903.250000,80.000000,22.000000,10.000000,2022.0,15.000000,44.000000,90.0,1.000000,...,2.000000,30.000000,3.000000,4711.000000,5211.000000,52.000000,142.639988,141.301163,140.473053,147.250000
max,1.013348e+06,35022.000000,5500.000000,31.000000,12.000000,2022.0,23.000000,59.000000,90.0,1.000000,...,4.000000,55.000000,3.000000,9511.000000,7250.000000,72.000000,507.000000,507.000000,507.000000,236.000000

In [5]:
# Create CSV containing column names and their types or nature as interpreted by pandas
df.dtypes.to_csv(path_or_buf="/kaggle/working/Pakistan_2022_full_data_columns.csv",header=["Type"],index_label="Name")

In [6]:
# Create CSV file 
df.to_csv(path_or_buf="/kaggle/working/Pakistan_2022_full_data.csv")